version: '3.8'

services:
  app:
    build: .
    container_name: pfe_app
    working_dir: /app
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173" 
